# overlays/dev/kustomization.yml
resources:
- ../../base
namespace: default
namePrefix: dev-
patches:
- path: patchDeployment.yaml
# - path: patchIngress.yaml
# path: patchService.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    env: dev
replicas:
  - name: dev-demo-app
    count: 20