apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app     # 반드시 base와 동일한 이름으로!
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: demo-app   # base의 container name과 일치해야 함
          image: 120653558546.dkr.ecr.ap-south-1.amazonaws.com/my-app:latest
      imagePullSecrets:
        - name: my-reg
