apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo2-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: my-app=120653558546.dkr.ecr.ap-south-1.amazonaws.com/my-app
    argocd-image-updater.argoproj.io/my-app.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  source:
    repoURL: https://github.com/zzzcolcol/argocd.git
    targetRevision: HEAD
    path: overlays/dev
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
